version: '3.8'

services:
  api:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: nodemon server.js
    working_dir: /usr/src/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
